name: Verify Codebase

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify:
    name: Verify Codebase
    runs-on: macos-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
      - name: Test
        id: test
        run: swift test
      - name: Build
        id: build
        run: swift build
