name: Verify Codebase

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify:
    name: Verify Codebase
    runs-on: macos-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
      - name: Setup Swift
        id: setup-swift
        uses: swift-actions/setup-swift@v1
      - name: Setup Xcode
        id: setup-xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - name: Test
        id: test
        run: swift test
      - name: Build
        id: build
        run: swift build
